
services:
  - docker:dind
stages:
  - build_and_push
  - deploy_staging
  - deploy_production

#2
variables:
  REGISTRY: "registry.gitlab.com/new-aic-mvp2/web-app-react/aicollect-web-app"
  IMAGE_NAME: "registry.gitlab.com/new-aic-mvp2/web-app-react/aicollect-web-app:latest"

before_script:
  - docker login $REGISTRY  --username ${DOCKER_USER} --password ${DOCKER_USER_PASSWORD}
#4
build_and_push:
  stage: build_and_push
  only:
    - develop
  script:
    - docker build -t $REGISTRY .
    - docker push $REGISTRY

#5 

deploy_staging:
  stage: deploy_staging
  tags: 
    - Deployment
    - Staging
  only:
    - develop
  script:
    - chmod og= $SSHKEY
    - docker run --rm docker:git  apk update && docker run --rm docker:git  apk add openssh-client
    - ssh -i $SSHKEY  -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "docker login $REGISTRY  --username ${DOCKER_USER} --password ${DOCKER_USER_PASSWORD}"
    - ssh -i $SSHKEY  -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "docker pull  registry.gitlab.com/new-aic-mvp2/web-app-react/aicollect-web-app:latest"
    - ssh -i $SSHKEY  -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "docker run -d -p 8001:3000 --restart always  --name aic_clientAPP  registry.gitlab.com/new-aic-mvp2/web-app-react/aicollect-web-app:latest"
  environment:
    name: staging 
    url: https://testclient.aicollectapp.com
